name: "[ Release ] → gh-pages"

on:
  push:
    branches: [release]
  workflow_dispatch:

jobs:
  build-release:
    name: build and push to gh-pages
    uses: GDQuest/learn-gdscript/.github/workflows/BuildGodot.yaml@github-actions-v1.1
    with:
      sub_build_path: ''
      watermark: $GITHUB_REPOSITORY:release:$GITHUB_REF_NAME:$GITHUB_SHA
  export-release:
    name: build and push artifacts
    uses: GDQuest/learn-gdscript/.github/workflows/ExportGodot.yaml@f8472b1592b536745fbebbf8e1f71a86b808abce