name: "[ Staging ] → gh-pages"

on:
  push:
    branches: [staging]
  workflow_dispatch:

jobs:
  build-staging:
    name: build and push to gh-pages
    uses: GDQuest/learn-gdscript/.github/workflows/BuildGodot.yaml@0f6c2ddea508c33c4c7e78b265a300a27359a547
    with:
      sub_build_path: /staging
      watermark: $GITHUB_REPOSITORY:staging:$GITHUB_REF_NAME:$GITHUB_SHA
      override_file: override.staging.cfg