name: "[ Staging ] → gh-pages"

on:
  push:
    branches: [staging]
  workflow_dispatch:

jobs:
  build-staging:
    name: build and push to gh-pages
    uses: Xananax/godot-ci-test/.github/workflows/BuildGodot.yaml@a3f4a055f38391b622e960e9c0939cafc455e522
    with:
      sub_build_path: /staging
      watermark: $GITHUB_REPOSITORY:staging:$GITHUB_REF_NAME:$GITHUB_SHA